chore(*): update task executables

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -6,6 +6,17 @@ cd "$(dirname "$0")/.."
 
 [ $? -eq 0 ] && export PWD="$(pwd)"
 
+echo 'Cleaning up...'
+
 . "$PWD/bin/clean"
 
+echo '
+Building...'
+
+printf 'Creating `./dist` artifact ... '
+
 cp -R "$PWD/src" "$PWD/dist"
+
+[ $? -ne 0 ] && echo 'failed.' && exit 1
+
+echo 'success.'
diff --git a/bin/clean b/bin/clean
--- a/bin/clean
+++ b/bin/clean
@@ -6,6 +6,21 @@ cd "$(dirname "$0")/.."
 
 [ $? -eq 0 ] && export PWD="$(pwd)"
 
+printf 'Removing `.DS_Store` files ... '
+
 find "$PWD" -name '.DS_Store' -type f -exec rm {} +
 
-rm -rf "$PWD/dist"
+if [ $? -eq 0 ]
+  then
+    echo 'success.'
+else
+  echo 'failed.'
+fi
+
+printf 'Removing `./dist` artifact ... '
+
+rm -fr "$PWD/dist"
+
+[ $? -ne 0 ] && echo 'failed.' && exit 1
+
+echo 'success.'
diff --git a/bin/uninstall b/bin/uninstall
--- a/bin/uninstall
+++ b/bin/uninstall
@@ -1,3 +1,21 @@
 #!/bin/sh
 
-rm -rf "$PROFILES/bonprix.sh"
+if [ -z ${PROFILES:+PROFILES} ] || [ ! -d "$PROFILES" ] || [ ! -w "$PROFILES" ]
+  then
+    echo "$(cat <<EOF
+Your profiles directory is undefined or not writable. Please make sure that
+dotfiles is correctly installed and the user permissions are properly set. Then
+try again.
+EOF
+    )" >&2
+
+    exit 1
+fi
+
+printf 'Removing symbolic link ... '
+
+rm -fr "$PROFILES/bonprix.sh"
+
+[ $? -ne 0 ] && echo 'failed.' && exit 1
+
+echo 'success.'
