feat(bin): provide result functions

diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -46,6 +46,16 @@ EOF
     exit 126
 fi
 
+fail () {
+  echo 'failed.'
+
+  exit 1
+}
+
+succeed () {
+  echo 'success.'
+}
+
 specs="$PWD/lib/test"
 
 if [ $# -lt 1 ]
